name: 'Validate'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/**'
      - '.golangci.yaml'
      - '*.go'
      - 'go.*'

env:
  GO_VERSION: '1.24'
  LINTER_VERSION: 'v2.2'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 'Build package'
        run: go build ./

  lint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Run linters'
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.LINTER_VERSION }}
          args: --timeout=2m

  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: 'Test'
        run: ./scripts/test.sh

      - name: 'Upload coverage result'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          file: coverage.out
          format: golang
