name: 'Validate'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/**'
      - 'drivers/**'
      - '.golangci.yaml'
      - '*.go'
      - 'go.*'

env:
  PGX_DRIVER: './drivers/pgx/'
  SQL_DRIVER: './drivers/sql/'
  SQLX_DRIVER: './drivers/sqlx/'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: 'Build package'
        run: go build ./

      - name: 'Build pgx driver'
        run: go build ${{ env.PGX_DRIVER }}

      - name: 'Build sql driver'
        run: go build ${{ env.SQL_DRIVER }}

      - name: 'Build sqlx driver'
        run: go build ${{ env.SQLX_DRIVER }}

  prelint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Detect modules'
        id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest

    needs: prelint

    permissions:
      contents: read

    strategy:
      matrix:
        modules: ${{ fromJSON(needs.prelint.outputs.modules) }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Run linters'
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=2m

  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: 'Test'
        run: ./scripts/test.sh
